name: Build and package Scissors.Desktop Windows installer

on:
    push:
        tags:
            - "desktop-v*"
    workflow_dispatch:

env:
    APP_NAME: scissors-desktop

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: read

        steps:
            - name: Build desktop app
              run: echo "Not implemented"
