name: Build and package Scissors mobile application

on:
    push:
        tags:
            - "mobile-v*"
    workflow_dispatch:

env:
    APP_NAME: scissors-mobile

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: read

        steps:
            - name: Build mobile app
              run: echo "Not implemented"
